services:
  postgres:
    image: postgres:16-alpine
    container_name: users-auth-db
    environment:
      POSTGRES_DB: users_auth
      POSTGRES_USER: campus
      POSTGRES_PASSWORD: campus123
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data   # los datos no se pierden al reiniciar
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U campus -d users_auth"]
      interval: 5s
      timeout: 5s
      retries: 10

  users-auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: users-auth
    ports:
      - "8081:8081"
    volumes:
      - ./:/app              # monta tu código: los cambios entran al contenedor
      - m2-cache:/root/.m2   # no vuelve a descargar dependencias
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
      - SPRING_DEVTOOLS_RESTART_POLL_INTERVAL=2s
      - SPRING_DEVTOOLS_RESTART_QUIET_PERIOD=1s
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/users_auth
      - SPRING_DATASOURCE_USERNAME=campus
      - SPRING_DATASOURCE_PASSWORD=campus123
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  m2-cache:
  pg-data: